name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: artimech-website
  GAR_LOCATION: us-central1
  SERVICE: artimech-website
  REGION: us-central1

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

    - name: Configure Docker to use gcloud as a credential helper
      run: |-
        gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev

    - name: Build and push container
      run: |-
        docker build -t "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$SERVICE/$SERVICE:$GITHUB_SHA" ./
        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$SERVICE/$SERVICE:$GITHUB_SHA"

    - name: Deploy to Cloud Run
      run: |-
        gcloud run deploy $SERVICE \
          --image=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$SERVICE/$SERVICE:$GITHUB_SHA \
          --region=$REGION \
          --service-account=artimech-deployer@$PROJECT_ID.iam.gserviceaccount.com \
          --allow-unauthenticated \
          --port=3000 \
          --cpu=1 \
          --memory=512Mi \
          --min-instances=0 \
          --max-instances=10 \
          --set-env-vars="NEXT_PUBLIC_GA_ID=${{ secrets.GA_MEASUREMENT_ID }}" 